### PR TITLE
Optionally compile with curl support

### LINKED ISSUE #53: Handle missing curl headers
A customer has an issue where they don't have the dev headers for curl installed, so compilation fails.

```
scout_curl_wrapper.c:8:10: fatal error: curl/curl.h: No such file or directory
```

To add headers: `sudo apt-get install libcurl4-openssl-dev`

Beyond the quick fix of adding the header, we need to add support for compiling the rest of the extension without the curl header present. Add a check to the configure script and avoid building the curl instruments if the prereq headers are missing.

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #53

### CODE REVIEW

File: zend_scoutapm.h [hunk 1]
```diff
@@ -8,9 +8,7 @@
 #ifndef ZEND_SCOUTAPM_H
 #define ZEND_SCOUTAPM_H
 
-#ifdef HAVE_CONFIG_H
```
Comment (cschneid) [inline zend_scoutapm.h]: What's the HAVE_CONFIG_H define?

Comment (asgrim) [reply zend_scoutapm.h]: It is defined by autoconf, but since exts are always built with autoconf, this can be omitted (if the `#ifdef` is kept, it confuses CLion who thinks that `HAVE_CONFIG_H` is *not* defined)
